# Generated by Django 4.2.4 on 2023-09-28 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lodge_user_lodgereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgeAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lodge',
            name='amenities',
            field=models.ManyToManyField(to='core.lodgeamenity'),
        ),
    ]
