# Generated by Django 4.2.4 on 2023-09-29 16:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.lodge_image_file, validators=[core.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to=core.models.student_image_file, validators=[core.models.validate_image]),
        ),
    ]
