# Generated by Django 4.2.4 on 2023-09-27 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_year_of_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('total_rooms', models.IntegerField()),
                ('rent_rate', models.IntegerField()),
                ('caretaker_number', models.CharField(max_length=11, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lodge',
                'verbose_name_plural': 'Lodges',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='lodges',
            field=models.ManyToManyField(to='core.lodge'),
        ),
    ]
