# Generated by Django 4.2.4 on 2023-09-27 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lodge_customuser_lodges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
