# Generated by Django 4.2.4 on 2023-09-28 18:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_lodge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.object_image_file),
        ),
    ]
