# Generated by Django 4.2.4 on 2023-09-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=20, null=True)),
                ('age', models.IntegerField(default=0)),
                ('department', models.CharField(max_length=100)),
                ('year_of_admission', models.CharField(max_length=4)),
            ],
        ),
    ]
